[package]
name = "did"
version = "0.0.1"

[addresses]
my_addr = "0xe4fba1c6a4ecc1ff67a7160f46cb74cbb6d350e07237e6c72b6aff2c7f826d6e"
std = "0x1"
aptos_framework = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/move-stdlib/", rev="aptos-cli-v0.3.4" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v0.3.4" }
