[package]
name = "did"
version = "0.0.1"

[addresses]
my_addr = "5a05b2ec94017f9e0a2cb20132ae15bc492f4527971c1296afdd084ac246a09a"
std = "0x1"
aptos_framework = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/move-stdlib/", rev="aptos-cli-v0.3.4" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v0.3.4" }
